name: Build and publish snap to snap store
on:
  push:
  pull_request:

jobs:
  build:
    name: Build snap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build snap
        id: snapcraft
        uses: snapcore/action-build@v1

      - name: Archive snap artifact
        uses: actions/upload-artifact@v2
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}

  publish:
    name: Publish snap to snap store
    if: ${{ github.ref == 'refs/heads/stable' && github.repository_owner == 'octave-snap' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download snap artifact
        id: download
        uses: actions/download-artifact@v2
        with:
          name: snap

      - name: Expand the full file name of the snap
        id: expand
        run: echo "::set-output name=snap::$(ls ${{ steps.download.outputs.download-path }}/octave_*.snap)"

      - name: Compute the short git commit hash
        id: git
        run: echo "::set-output name=commit::$(git rev-parse --short=12 $GITHUB_REF)"

      - name: Publish snap builds to a unique branch on the edge channel
        uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{ steps.expand.outputs.snap }}
          release: edge/stable-${{ steps.git.outputs.commit }}

  test:
    name: Test snap
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download snap artifact
        id: download
        uses: actions/download-artifact@v2
        with:
          name: snap

      - name: Expand the full file name of the snap
        id: expand
        run: echo "::set-output name=snap::$(ls ${{ steps.download.outputs.download-path }}/octave_*.snap)"

      - name: Install the snap and smoke test octave
        run: |
          sudo snap install --dangerous ${{ steps.expand.outputs.snap }}
          /snap/bin/octave --version
