name: Build snap
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build snap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build snap
        id: snapcraft
        uses: snapcore/action-build@v1

      - name: Archive snap artifact
        uses: actions/upload-artifact@v2
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}
