name: Build and publish snap to snap store
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build snap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build snap
        id: snapcraft
        uses: snapcore/action-build@v1

      - name: Archive snap artifact
        uses: actions/upload-artifact@v2
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}

  publish:
    name: Publish snap to snap store
    if: ${{ github.ref == 'refs/heads/main' && github.repository_owner == 'octave-snap' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download snap artifact
        id: download
        uses: actions/download-artifact@v2
        with:
          name: snap

      - name: Expand the full file name of the snap
        id: expand
        run: echo "::set-output name=snap::$(ls ${{ steps.download.outputs.download-path }}/octave_*.snap)"

      - name: Publish unstable snap builds to edge channel
        uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{ steps.expand.outputs.snap }}
          release: edge
